[package]
name = "charon-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
charon-lib.workspace = true
tempfile = "3.20.0"
